### PR TITLE
Change __construct($domain);

### PR DESCRIPTION
**Pull request by Beheer80**
Get common name without www.

### CODE REVIEW

**Comment by felixarntz** [comment]
Thanks for the PR! However I'm curious what the benefit of this would be. The certificate is generated for both variants anyway.

**Comment by t-me** [comment]
If you want to access the site from "example.com" and the common name is "www.example.com" you get a SSL error on some browsers.

With the common name "example.com" you don't have the error because "example.com" is common with "www.example.com" also some hosting providers are giving a error that the common name does not match

**Comment by ericofranco** [comment]
The www. and non www. thing is already managed in another part of the code:

https://github.com/felixarntz/wp-encrypt/blob/master/inc/WPENC/Core/Util.php#L301

So looks like this change dont make sense (if you are talking about the same version - sorry not very familiar with github )

There is a issue I just opened as it is not generating www. certs for non us domains like .com.br:

https://github.com/felixarntz/wp-encrypt/issues/33

That may solve the www. problem.

**Comment by felixarntz** [comment]
The bug mentioned above is going to be fixed through #42, so I'll close this one.

**Pull request closed without merging**
